In [1]:
pip install openpyxl

Requirement already satisfied: openpyxl in c:\Users\Usuario\anaconda3\Lib\site-packages (3.1.5)
Requirement already satisfied: et_xmlfile in c:\Users\Usuario\anaconda3\Lib\site-packages (from openpyxl) (2.0.0)
Note: you may need to restart the kernel to use updated packages.

In [2]:
import pandas as pd

In [3]:
ruta = "C:/Users/Usuario/Downloads/Nueva carpeta/BD_SERPAVI_2011-2024.xlsx"
xls = pd.ExcelFile(ruta)
print(xls.sheet_names)

['Metadatos', 'CCAA', 'Provincias', 'Municipios', 'Distritos', 'Secciones censales']

In [ ]:
df_metadatos = pd.read_excel(ruta, sheet_name='Metadatos')
print(df_metadatos.shape)
print(df_metadatos.columns)
df_metadatos.head(40)

In [ ]:
print(df_metadatos.iloc[1, 0]); print(df_metadatos.iloc[17, 0]); print(df_metadatos.iloc[38, 0]); print(df_metadatos.iloc[39, 0])

In [ ]:
df = pd.read_excel(ruta, sheet_name='Secciones censales')
print(df.shape)
print(df.columns)

In [8]:
df['CUSEC'] = df['CUSEC'].astype(str).str.zfill(10)
# con zfill evito errores al cambiar el dato a tipo str, y no pierdo los ceros a la izquierda, por lo tanto no pierdo datos.

In [ ]:
filtro_municipio_madrid =df['CUSEC'].str.startswith("28079")
print(filtro_municipio_madrid.sum())

2442

In [29]:
madrid = df.loc[filtro_municipio_madrid].copy()
madrid.head()

,CPRO,LITPRO,CUMUN,LITMUN,CUSEC,BI_ALVHEPCO_TVC_11,BI_ALVHEPCO_TVU_11,ALQM2_LV_M_VC_11,ALQM2_LV_25_VC_11,ALQM2_LV_75_VC_11,...,ALQTBID12_75_VC_24,ALQTBID12_M_VU_24,ALQTBID12_25_VU_24,ALQTBID12_75_VU_24,SLVM2_M_VC_24,SLVM2_25_VC_24,SLVM2_75_VC_24,SLVM2_M_VU_24,SLVM2_25_VU_24,SLVM2_75_VU_24
17817,28,Madrid,28079,Madrid,2807901001,92.0,0.0,11.368421,7.407407,15.805556,...,1751.136667,NaN,NaN,NaN,74.0,55.50,114.5,NaN,NaN,NaN
17818,28,Madrid,28079,Madrid,2807901002,64.0,0.0,12.000000,8.888889,16.428571,...,1273.642186,NaN,NaN,NaN,55.0,38.50,82.5,NaN,NaN,NaN
17819,28,Madrid,28079,Madrid,2807901003,156.0,0.0,12.029344,7.757619,16.298952,...,1417.887427,NaN,NaN,NaN,63.5,52.00,86.0,NaN,NaN,NaN
17820,28,Madrid,28079,Madrid,2807901004,101.0,0.0,13.392857,9.496394,17.973684,...,1739.750629,NaN,NaN,NaN,67.0,42.25,108.0,NaN,NaN,NaN
17821,28,Madrid,28079,Madrid,2807901006,127.0,0.0,12.500000,9.374642,15.014949,...,1510.135135,NaN,NaN,NaN,67.0,49.00,99.5,NaN,NaN,NaN

In [36]:
madrid['COD_SECCION'] = madrid['CUSEC'].str[7:10]
madrid['COD_DISTRITO'] = madrid['CUSEC'].str[5:7]
madrid.head(40)

,CPRO,LITPRO,CUMUN,LITMUN,CUSEC,BI_ALVHEPCO_TVC_11,BI_ALVHEPCO_TVU_11,ALQM2_LV_M_VC_11,ALQM2_LV_25_VC_11,ALQM2_LV_75_VC_11,...,ALQTBID12_25_VU_24,ALQTBID12_75_VU_24,SLVM2_M_VC_24,SLVM2_25_VC_24,SLVM2_75_VC_24,SLVM2_M_VU_24,SLVM2_25_VU_24,SLVM2_75_VU_24,COD_DISTRITO,COD_SECCION
17817,28,Madrid,28079,Madrid,2807901001,92.0,0.0,11.368421,7.407407,15.805556,...,NaN,NaN,74.0,55.50,114.50,NaN,NaN,NaN,01,001
17818,28,Madrid,28079,Madrid,2807901002,64.0,0.0,12.000000,8.888889,16.428571,...,NaN,NaN,55.0,38.50,82.50,NaN,NaN,NaN,01,002
17819,28,Madrid,28079,Madrid,2807901003,156.0,0.0,12.029344,7.757619,16.298952,...,NaN,NaN,63.5,52.00,86.00,NaN,NaN,NaN,01,003
17820,28,Madrid,28079,Madrid,2807901004,101.0,0.0,13.392857,9.496394,17.973684,...,NaN,NaN,67.0,42.25,108.00,NaN,NaN,NaN,01,004
17821,28,Madrid,28079,Madrid,2807901006,127.0,0.0,12.500000,9.374642,15.014949,...,NaN,NaN,67.0,49.00,99.50,NaN,NaN,NaN,01,006
17822,28,Madrid,28079,Madrid,2807901007,54.0,0.0,12.285895,9.684322,15.255755,...,NaN,NaN,64.0,51.00,84.00,NaN,NaN,NaN,01,007
17823,28,Madrid,28079,Madrid,2807901008,76.0,0.0,13.622963,10.327273,16.025641,...,NaN,NaN,53.0,41.00,71.50,NaN,NaN,NaN,01,008
17824,28,Madrid,28079,Madrid,2807901009,102.0,2.0,12.732185,9.331359,17.338041,...,NaN,NaN,74.0,46.00,97.00,NaN,NaN,NaN,01,009
17825,28,Madrid,28079,Madrid,2807901011,86.0,0.0,12.422840,8.522204,15.736035,...,NaN,NaN,58.0,44.50,84.50,NaN,NaN,NaN,01,011
17826,28,Madrid,28079,Madrid,2807901012,38.0,0.0,13.979978,10.516441,18.556174,...,NaN,NaN,68.0,51.00,88.75,NaN,NaN,NaN,01,012
17827,28,Madrid,28079,Madrid,2807901013,107.0,0.0,14.098765,9.524789,17.771550,...,NaN,NaN,53.0,41.00,74.75,NaN,NaN,NaN,01,013
17828,28,Madrid,28079,Madrid,2807901014,109.0,0.0,12.500000,9.661017,16.666667,...,NaN,NaN,50.0,41.00,76.00,NaN,NaN,NaN,01,014
17829,28,Madrid,28079,Madrid,2807901015,102.0,0.0,14.096073,10.527090,17.088060,...,NaN,NaN,52.0,38.00,70.75,NaN,NaN,NaN,01,015
17830,28,Madrid,28079,Madrid,2807901016,86.0,0.0,12.971698,8.474260,17.028846,...,NaN,NaN,65.0,45.00,85.00,NaN,NaN,NaN,01,016
17831,28,Madrid,28079,Madrid,2807901018,117.0,0.0,14.305553,10.645015,16.995710,...,NaN,NaN,52.0,42.00,69.00,NaN,NaN,NaN,01,018
17832,28,Madrid,28079,Madrid,2807901019,132.0,0.0,12.621442,10.010638,16.576087,...,NaN,NaN,53.0,41.00,71.00,NaN,NaN,NaN,01,019
17833,28,Madrid,28079,Madrid,2807901020,74.0,0.0,12.322807,8.443505,16.117811,...,NaN,NaN,47.0,37.00,74.00,NaN,NaN,NaN,01,020
17834,28,Madrid,28079,Madrid,2807901021,127.0,0.0,13.086807,10.239574,15.716044,...,NaN,NaN,54.0,44.00,76.00,NaN,NaN,NaN,01,021
17835,28,Madrid,28079,Madrid,2807901022,72.0,0.0,13.072917,10.389610,15.384615,...,NaN,NaN,60.0,44.50,75.00,NaN,NaN,NaN,01,022
17836,28,Madrid,28079,Madrid,2807901023,83.0,0.0,12.000000,8.442857,15.342094,...,NaN,NaN,53.0,40.00,64.00,NaN,NaN,NaN,01,023
17837,28,Madrid,28079,Madrid,2807901024,75.0,0.0,13.548387,10.833333,16.037736,...,NaN,NaN,53.0,43.75,68.00,NaN,NaN,NaN,01,024
17838,28,Madrid,28079,Madrid,2807901025,83.0,0.0,10.852575,7.499270,13.766340,...,NaN,NaN,65.0,50.00,88.25,NaN,NaN,NaN,01,025
17839,28,Madrid,28079,Madrid,2807901026,87.0,0.0,12.394599,8.536448,16.263587,...,NaN,NaN,69.0,47.50,101.00,NaN,NaN,NaN,01,026
17840,28,Madrid,28079,Madrid,2807901027,84.0,0.0,14.166667,9.684343,17.426215,...,NaN,NaN,56.0,42.00,85.50,NaN,NaN,NaN,01,027
17841,28,Madrid,28079,Madrid,2807901028,88.0,0.0,10.959133,7.694366,13.784153,...,NaN,NaN,62.0,41.00,89.00,NaN,NaN,NaN,01,028
17842,28,Madrid,28079,Madrid,2807901029,83.0,0.0,12.280702,7.703488,15.384615,...,NaN,NaN,51.5,39.00,75.00,NaN,NaN,NaN,01,029
17843,28,Madrid,28079,Madrid,2807901030,109.0,0.0,9.756515,6.796117,12.209302,...,NaN,NaN,62.0,47.00,78.00,NaN,NaN,NaN,01,030
17844,28,Madrid,28079,Madrid,2807901031,46.0,0.0,10.690789,7.500579,16.144918,...,NaN,NaN,51.0,39.25,60.75,NaN,NaN,NaN,01,031
17845,28,Madrid,28079,Madrid,2807901032,137.0,0.0,13.088742,9.569239,16.113329,...,NaN,NaN,53.5,42.00,68.00,NaN,NaN,NaN,01,032
17846,28,Madrid,28079,Madrid,2807901033,84.0,0.0,11.585227,8.545737,14.979291,...,NaN,NaN,49.0,39.00,65.00,NaN,NaN,NaN,01,033
17847,28,Madrid,28079,Madrid,2807901034,79.0,0.0,13.113557,9.804433,16.359401,...,NaN,NaN,40.0,34.00,53.25,NaN,NaN,NaN,01,034
17848,28,Madrid,28079,Madrid,2807901035,81.0,0.0,12.500000,9.547774,14.803861,...,NaN,NaN,49.0,38.00,59.50,NaN,NaN,NaN,01,035
17849,28,Madrid,28079,Madrid,2807901036,85.0,0.0,12.260000,8.440848,16.291709,...,NaN,NaN,43.0,36.00,52.00,NaN,NaN,NaN,01,036
17850,28,Madrid,28079,Madrid,2807901037,75.0,0.0,13.235294,9.741667,16.112007,...,NaN,NaN,46.0,37.00,60.00,NaN,NaN,NaN,01,037
17851,28,Madrid,28079,Madrid,2807901038,62.0,0.0,13.235294,10.824393,16.274578,...,NaN,NaN,40.0,32.25,56.00,NaN,NaN,NaN,01,038
17852,28,Madrid,28079,Madrid,2807901039,67.0,0.0,11.345668,8.033441,14.749650,...,NaN,NaN,48.0,37.00,63.00,NaN,NaN,NaN,01,039
17853,28,Madrid,28079,Madrid,2807901040,41.0,0.0,12.619048,8.555195,15.964674,...,NaN,NaN,49.5,37.75,66.50,NaN,NaN,NaN,01,040
17854,28,Madrid,28079,Madrid,2807901041,76.0,1.0,13.294553,10.000000,16.947805,...,NaN,NaN,47.0,35.00,67.00,NaN,NaN,NaN,01,041
17855,28,Madrid,28079,Madrid,2807901042,74.0,0.0,12.158400,8.678417,14.084881,...,NaN,NaN,50.0,41.00,68.00,NaN,NaN,NaN,01,042
17856,28,Madrid,28079,Madrid,2807901043,66.0,0.0,10.724137,6.989056,12.801473,...,NaN,NaN,53.0,39.00,65.00,NaN,NaN,NaN,01,043