In [2]:
pip install openpyxl

Requirement already satisfied: openpyxl in c:\Users\Usuario\anaconda3\Lib\site-packages (3.1.5)
Requirement already satisfied: et_xmlfile in c:\Users\Usuario\anaconda3\Lib\site-packages (from openpyxl) (2.0.0)
Note: you may need to restart the kernel to use updated packages.

In [3]:
import pandas as pd

In [4]:
ruta = "C:/Users/Usuario/Downloads/Nueva carpeta/BD_SERPAVI_2011-2024.xlsx"
xls = pd.ExcelFile(ruta)
print(xls.sheet_names)

['Metadatos', 'CCAA', 'Provincias', 'Municipios', 'Distritos', 'Secciones censales']

In [5]:
df_metadatos = pd.read_excel(ruta, sheet_name='Metadatos')
print(df_metadatos.shape)
print(df_metadatos.columns)
df_metadatos.head(40)

(40, 3)
Index(['Sistema Estatal Índices Alquiler de Vivienda', 'Unnamed: 1',
       'Unnamed: 2'],
      dtype='str')

,Sistema Estatal Índices Alquiler de Vivienda,Unnamed: 1,Unnamed: 2
0,(Explotación estadística de fuentes tributarias),NaN,NaN
1,Datos rentas y arrendamientos Modelo 100 por a...,NaN,NaN
2,Diseño de registro,NaN,NaN
3,Código,Denominación / definición,Tipo
4,CUSEC_R,Código único de Sección Censal Censo Población...,VARCHAR(10)
5,CUSEC,Código único de Sección Censal Censo Población...,INT
6,CUMUN,Código único de Municipio Censo Población 2021...,INT
7,CSEC,Código de Sección Censal Censo Población 2021 ...,INT
8,CDIS,Código de Distrito Censal Censo Población 2021...,INT
9,CMUN,Código Municipio Censo Población 2021 INE (num...,INT
10,CPRO,Código de Provincia Censo Población 2021 INE (...,INT
11,CUSEC,Código de Sección Censal Censo Población 2021 ...,INT
12,CCA,Código único de Comunidad Autónoma Censo Pobla...,INT
13,CUDIS,Código único de Distrito Censal Censo Població...,INT
14,NPRO,Nombre de Provincia Censo Población 2021 INE,VARCHAR(50)
15,NCA,Nombre de Comunidad Autónoma Censo Población 2...,VARCHAR(50)
16,NMUN,Nombre de Municipio Censo Población 2021 INE,VARCHAR(50)
17,Las siguientes medidas son para el subconjunto...,NaN,NaN
18,BI_ALVHEPCO_TVC_AA,Recuento subconjunto alquiler Grupo GGT01 VC: ...,INT
19,BI_ALVHEPCO_TVU_AA,Recuento subconjunto alquiler Grupo GGT01 VU: ...,INT
20,ALQM2mes_LV_M_VC_AA,Alquiler mensual m2 mediano m2 Grupo GGT01 VC:...,DOBLE
21,ALQM2mes_LV_25_VC_AA,Alquiler mensual m2 percentil 25 Grupo GGT01 V...,DOBLE
22,ALQM2mes_LV_75_VC_AA,Alquiler mensual m2 percentil 75 Grupo GGT01 V...,DOBLE
23,ALQM2mes_LV_M_VU_AA,Alquiler mensual m2 mediano m2 Grupo GGT01 VU:...,DOBLE
24,ALQM2mes_LV_25_VU_AA,Alquiler mensual m2 percentil 25 Grupo GGT01 V...,DOBLE
25,ALQM2mes_LV_75_VU_AA,Alquiler mensual m2 percentil 75 Grupo GGT01 V...,DOBLE
26,ALQTBID12_M_VC_AA,Alquiler mensual todo el bien inmueble mediana...,DOBLE
27,ALQTBID12_25_VC_AA,Alquiler mensual todo el bien inmueble percent...,DOBLE
28,ALQTBID12_75_VC_AA,Alquiler mensual todo el bien inmueble percent...,DOBLE
29,ALQTBID12_M_VU_AA,Alquiler mensual todo el bien inmueble mediana...,DOBLE
30,ALQTBID12_25_VU_AA,Alquiler mensual todo el bien inmueble percent...,DOBLE
31,ALQTBID12_75_VU_AA,Alquiler mensual todo el bien inmueble percent...,DOBLE
32,SLVM2_M_VC_AA,Superficie m2 mediana Grupo GGT01 VC: Vivienda...,DOBLE
33,SLVM2_25_VC_AA,Superficie m2 percentil 25 Grupo GGT01 VC: Viv...,DOBLE
34,SLVM2_75_VC_AA,Superficie m2 percentil 75 Grupo GGT01 VC: Viv...,DOBLE
35,SLVM2_M_VU_AA,Superficie m2 mediana Grupo GGT01 VU: Vivienda...,DOBLE
36,SLVM2_25_VU_AA,Superficie m2 percentil 25 Grupo GGT01 VU: Viv...,DOBLE
37,SLVM2_75_VU_AA,Superficie m2 percentil 75 Grupo GGT01 VU: Viv...,DOBLE
38,--> La denominación del campo se marca al fina...,NaN,NaN
39,Nota: Este archivo 2026-03_09_bd_SERPAVI_2011-...,NaN,NaN

In [6]:
print(df_metadatos.iloc[1, 0]); print(df_metadatos.iloc[17, 0]); print(df_metadatos.iloc[38, 0]); print(df_metadatos.iloc[39, 0])

Datos rentas y arrendamientos Modelo 100 por año Total: Los bienes inmuebles que se agregan son aquellos que tienen información tanto en la fuente tributaria como en la catastral.
Las siguientes medidas son para el subconjunto de estudio del alquiler: bienes inmuebles con ingresos por arrendamiento para vivienda habitual (excluidos arrendamientoa a parientes).
--> La denominación del campo se marca al final con "_AA" para señalar el año
Nota: Este archivo 2026-03_09_bd_SERPAVI_2011-2024 - DEFINITIVO WEB_v2.xlsx únicamente incluye la corrección en la fecha de referencia del seccionado censal del INE utilizado (2021) en esta hoja de Metadatos (08/07/2026).

In [7]:
df = pd.read_excel(ruta, sheet_name='Secciones censales')
print(df.shape)
print(df.columns)

(36293, 285)
Index(['CPRO', 'LITPRO', 'CUMUN', 'LITMUN', 'CUSEC', 'BI_ALVHEPCO_TVC_11',
       'BI_ALVHEPCO_TVU_11', 'ALQM2_LV_M_VC_11', 'ALQM2_LV_25_VC_11',
       'ALQM2_LV_75_VC_11',
       ...
       'ALQTBID12_75_VC_24', 'ALQTBID12_M_VU_24', 'ALQTBID12_25_VU_24',
       'ALQTBID12_75_VU_24', 'SLVM2_M_VC_24', 'SLVM2_25_VC_24',
       'SLVM2_75_VC_24', 'SLVM2_M_VU_24', 'SLVM2_25_VU_24', 'SLVM2_75_VU_24'],
      dtype='str', length=285)

In [8]:
df['CUSEC'] = df['CUSEC'].astype(str).str.zfill(10)
# con zfill evito errores al cambiar el dato a tipo str, y no pierdo los ceros a la izquierda, por lo tanto no pierdo datos.

In [9]:
filtro_municipio_madrid =df['CUSEC'].str.startswith("28079")
print(filtro_municipio_madrid.sum())

2442

In [10]:
madrid = df.loc[filtro_municipio_madrid].copy()
madrid.head()

,CPRO,LITPRO,CUMUN,LITMUN,CUSEC,BI_ALVHEPCO_TVC_11,BI_ALVHEPCO_TVU_11,ALQM2_LV_M_VC_11,ALQM2_LV_25_VC_11,ALQM2_LV_75_VC_11,...,ALQTBID12_75_VC_24,ALQTBID12_M_VU_24,ALQTBID12_25_VU_24,ALQTBID12_75_VU_24,SLVM2_M_VC_24,SLVM2_25_VC_24,SLVM2_75_VC_24,SLVM2_M_VU_24,SLVM2_25_VU_24,SLVM2_75_VU_24
17817,28,Madrid,28079,Madrid,2807901001,92.0,0.0,11.368421,7.407407,15.805556,...,1751.136667,NaN,NaN,NaN,74.0,55.50,114.5,NaN,NaN,NaN
17818,28,Madrid,28079,Madrid,2807901002,64.0,0.0,12.000000,8.888889,16.428571,...,1273.642186,NaN,NaN,NaN,55.0,38.50,82.5,NaN,NaN,NaN
17819,28,Madrid,28079,Madrid,2807901003,156.0,0.0,12.029344,7.757619,16.298952,...,1417.887427,NaN,NaN,NaN,63.5,52.00,86.0,NaN,NaN,NaN
17820,28,Madrid,28079,Madrid,2807901004,101.0,0.0,13.392857,9.496394,17.973684,...,1739.750629,NaN,NaN,NaN,67.0,42.25,108.0,NaN,NaN,NaN
17821,28,Madrid,28079,Madrid,2807901006,127.0,0.0,12.500000,9.374642,15.014949,...,1510.135135,NaN,NaN,NaN,67.0,49.00,99.5,NaN,NaN,NaN

In [11]:
madrid['COD_SECCION'] = madrid['CUSEC'].str[7:10]
madrid['COD_DISTRITO'] = madrid['CUSEC'].str[5:7]
madrid.head()

,CPRO,LITPRO,CUMUN,LITMUN,CUSEC,BI_ALVHEPCO_TVC_11,BI_ALVHEPCO_TVU_11,ALQM2_LV_M_VC_11,ALQM2_LV_25_VC_11,ALQM2_LV_75_VC_11,...,ALQTBID12_25_VU_24,ALQTBID12_75_VU_24,SLVM2_M_VC_24,SLVM2_25_VC_24,SLVM2_75_VC_24,SLVM2_M_VU_24,SLVM2_25_VU_24,SLVM2_75_VU_24,COD_SECCION,COD_DISTRITO
17817,28,Madrid,28079,Madrid,2807901001,92.0,0.0,11.368421,7.407407,15.805556,...,NaN,NaN,74.0,55.50,114.5,NaN,NaN,NaN,001,01
17818,28,Madrid,28079,Madrid,2807901002,64.0,0.0,12.000000,8.888889,16.428571,...,NaN,NaN,55.0,38.50,82.5,NaN,NaN,NaN,002,01
17819,28,Madrid,28079,Madrid,2807901003,156.0,0.0,12.029344,7.757619,16.298952,...,NaN,NaN,63.5,52.00,86.0,NaN,NaN,NaN,003,01
17820,28,Madrid,28079,Madrid,2807901004,101.0,0.0,13.392857,9.496394,17.973684,...,NaN,NaN,67.0,42.25,108.0,NaN,NaN,NaN,004,01
17821,28,Madrid,28079,Madrid,2807901006,127.0,0.0,12.500000,9.374642,15.014949,...,NaN,NaN,67.0,49.00,99.5,NaN,NaN,NaN,006,01