In [1]:
pip install openpyxl

Requirement already satisfied: openpyxl in c:\Users\Usuario\anaconda3\Lib\site-packages (3.1.5)
Requirement already satisfied: et_xmlfile in c:\Users\Usuario\anaconda3\Lib\site-packages (from openpyxl) (2.0.0)
Note: you may need to restart the kernel to use updated packages.

In [2]:
import pandas as pd

In [3]:
ruta = "C:/Users/Usuario/Downloads/Nueva carpeta/BD_SERPAVI_2011-2024.xlsx"
xls = pd.ExcelFile(ruta)
print(xls.sheet_names)

['Metadatos', 'CCAA', 'Provincias', 'Municipios', 'Distritos', 'Secciones censales']

In [4]:
df_metadatos = pd.read_excel(ruta, sheet_name='Metadatos')
print(df_metadatos.shape)
print(df_metadatos.columns)
df_metadatos.head(40)

(40, 3)
Index(['Sistema Estatal Índices Alquiler de Vivienda', 'Unnamed: 1',
       'Unnamed: 2'],
      dtype='str')

,Sistema Estatal Índices Alquiler de Vivienda,Unnamed: 1,Unnamed: 2
0,(Explotación estadística de fuentes tributarias),NaN,NaN
1,Datos rentas y arrendamientos Modelo 100 por a...,NaN,NaN
2,Diseño de registro,NaN,NaN
3,Código,Denominación / definición,Tipo
4,CUSEC_R,Código único de Sección Censal Censo Población...,VARCHAR(10)
5,CUSEC,Código único de Sección Censal Censo Población...,INT
6,CUMUN,Código único de Municipio Censo Población 2021...,INT
7,CSEC,Código de Sección Censal Censo Población 2021 ...,INT
8,CDIS,Código de Distrito Censal Censo Población 2021...,INT
9,CMUN,Código Municipio Censo Población 2021 INE (num...,INT
10,CPRO,Código de Provincia Censo Población 2021 INE (...,INT
11,CUSEC,Código de Sección Censal Censo Población 2021 ...,INT
12,CCA,Código único de Comunidad Autónoma Censo Pobla...,INT
13,CUDIS,Código único de Distrito Censal Censo Població...,INT
14,NPRO,Nombre de Provincia Censo Población 2021 INE,VARCHAR(50)
15,NCA,Nombre de Comunidad Autónoma Censo Población 2...,VARCHAR(50)
16,NMUN,Nombre de Municipio Censo Población 2021 INE,VARCHAR(50)
17,Las siguientes medidas son para el subconjunto...,NaN,NaN
18,BI_ALVHEPCO_TVC_AA,Recuento subconjunto alquiler Grupo GGT01 VC: ...,INT
19,BI_ALVHEPCO_TVU_AA,Recuento subconjunto alquiler Grupo GGT01 VU: ...,INT
20,ALQM2mes_LV_M_VC_AA,Alquiler mensual m2 mediano m2 Grupo GGT01 VC:...,DOBLE
21,ALQM2mes_LV_25_VC_AA,Alquiler mensual m2 percentil 25 Grupo GGT01 V...,DOBLE
22,ALQM2mes_LV_75_VC_AA,Alquiler mensual m2 percentil 75 Grupo GGT01 V...,DOBLE
23,ALQM2mes_LV_M_VU_AA,Alquiler mensual m2 mediano m2 Grupo GGT01 VU:...,DOBLE
24,ALQM2mes_LV_25_VU_AA,Alquiler mensual m2 percentil 25 Grupo GGT01 V...,DOBLE
25,ALQM2mes_LV_75_VU_AA,Alquiler mensual m2 percentil 75 Grupo GGT01 V...,DOBLE
26,ALQTBID12_M_VC_AA,Alquiler mensual todo el bien inmueble mediana...,DOBLE
27,ALQTBID12_25_VC_AA,Alquiler mensual todo el bien inmueble percent...,DOBLE
28,ALQTBID12_75_VC_AA,Alquiler mensual todo el bien inmueble percent...,DOBLE
29,ALQTBID12_M_VU_AA,Alquiler mensual todo el bien inmueble mediana...,DOBLE
30,ALQTBID12_25_VU_AA,Alquiler mensual todo el bien inmueble percent...,DOBLE
31,ALQTBID12_75_VU_AA,Alquiler mensual todo el bien inmueble percent...,DOBLE
32,SLVM2_M_VC_AA,Superficie m2 mediana Grupo GGT01 VC: Vivienda...,DOBLE
33,SLVM2_25_VC_AA,Superficie m2 percentil 25 Grupo GGT01 VC: Viv...,DOBLE
34,SLVM2_75_VC_AA,Superficie m2 percentil 75 Grupo GGT01 VC: Viv...,DOBLE
35,SLVM2_M_VU_AA,Superficie m2 mediana Grupo GGT01 VU: Vivienda...,DOBLE
36,SLVM2_25_VU_AA,Superficie m2 percentil 25 Grupo GGT01 VU: Viv...,DOBLE
37,SLVM2_75_VU_AA,Superficie m2 percentil 75 Grupo GGT01 VU: Viv...,DOBLE
38,--> La denominación del campo se marca al fina...,NaN,NaN
39,Nota: Este archivo 2026-03_09_bd_SERPAVI_2011-...,NaN,NaN

In [5]:
print(df_metadatos.iloc[18, 1]); print(df_metadatos.iloc[17, 0]); print(df_metadatos.iloc[38, 0]); print(df_metadatos.iloc[39, 0])

Recuento subconjunto alquiler Grupo GGT01 VC: Vivienda Colectiva como tipología de más superficie
Las siguientes medidas son para el subconjunto de estudio del alquiler: bienes inmuebles con ingresos por arrendamiento para vivienda habitual (excluidos arrendamientoa a parientes).
--> La denominación del campo se marca al final con "_AA" para señalar el año
Nota: Este archivo 2026-03_09_bd_SERPAVI_2011-2024 - DEFINITIVO WEB_v2.xlsx únicamente incluye la corrección en la fecha de referencia del seccionado censal del INE utilizado (2021) en esta hoja de Metadatos (08/07/2026).

In [6]:
df = pd.read_excel(ruta, sheet_name='Secciones censales')
print(df.shape)
print(df.columns)

(36293, 285)
Index(['CPRO', 'LITPRO', 'CUMUN', 'LITMUN', 'CUSEC', 'BI_ALVHEPCO_TVC_11',
       'BI_ALVHEPCO_TVU_11', 'ALQM2_LV_M_VC_11', 'ALQM2_LV_25_VC_11',
       'ALQM2_LV_75_VC_11',
       ...
       'ALQTBID12_75_VC_24', 'ALQTBID12_M_VU_24', 'ALQTBID12_25_VU_24',
       'ALQTBID12_75_VU_24', 'SLVM2_M_VC_24', 'SLVM2_25_VC_24',
       'SLVM2_75_VC_24', 'SLVM2_M_VU_24', 'SLVM2_25_VU_24', 'SLVM2_75_VU_24'],
      dtype='str', length=285)

In [7]:
df['CUSEC'] = df['CUSEC'].astype(str).str.zfill(10)
# con zfill evito errores al cambiar el dato a tipo str, se colocan los ceros a la izquierda, por lo tanto no pierdo datos.

In [8]:
filtro_municipio_madrid =df['CUSEC'].str.startswith("28079")
print(filtro_municipio_madrid.sum())

2442

In [9]:
df_madrid = df.loc[filtro_municipio_madrid].copy()
df_madrid.head()
print(df_madrid.shape)
print(df_madrid.columns)

(2442, 285)
Index(['CPRO', 'LITPRO', 'CUMUN', 'LITMUN', 'CUSEC', 'BI_ALVHEPCO_TVC_11',
       'BI_ALVHEPCO_TVU_11', 'ALQM2_LV_M_VC_11', 'ALQM2_LV_25_VC_11',
       'ALQM2_LV_75_VC_11',
       ...
       'ALQTBID12_75_VC_24', 'ALQTBID12_M_VU_24', 'ALQTBID12_25_VU_24',
       'ALQTBID12_75_VU_24', 'SLVM2_M_VC_24', 'SLVM2_25_VC_24',
       'SLVM2_75_VC_24', 'SLVM2_M_VU_24', 'SLVM2_25_VU_24', 'SLVM2_75_VU_24'],
      dtype='str', length=285)

In [10]:
columna = list(df_madrid.columns[4:5])
columnas_restantes = df_madrid.columns[5:]

In [19]:
prefijos = ['BI_ALVHEPCO_TVC_', 'ALQM2_LV_M_VC_', 'ALQM2_LV_25_VC_', 'ALQM2_LV_75_VC_','ALQTBID12_M_VC_', 'ALQTBID12_25_VC', 'ALQTBID12_75_VC']
columnas_filtradas = []

for c in columnas_restantes:
    for p in prefijos:
        if c.startswith(p):
            año = c[-2:]
            if año.isdigit() and 15 <= int(año) <= 24:
                columnas_filtradas.append(c)
                break

columnas_unidas = columna + columnas_filtradas
df_alquileres_madrid = df_madrid[columnas_unidas]        
df_alquileres_madrid = df_alquileres_madrid.rename(columns={'CUSEC': 'COD_SEC_MADRID'})
df_alquileres_madrid

,COD_SEC_MADRID,BI_ALVHEPCO_TVC_15,ALQM2_LV_M_VC_15,ALQM2_LV_25_VC_15,ALQM2_LV_75_VC_15,ALQTBID12_M_VC_15,ALQTBID12_25_VC_15,ALQTBID12_75_VC_15,BI_ALVHEPCO_TVC_16,ALQM2_LV_M_VC_16,...,ALQTBID12_M_VC_23,ALQTBID12_25_VC_23,ALQTBID12_75_VC_23,BI_ALVHEPCO_TVC_24,ALQM2_LV_M_VC_24,ALQM2_LV_25_VC_24,ALQM2_LV_75_VC_24,ALQTBID12_M_VC_24,ALQTBID12_25_VC_24,ALQTBID12_75_VC_24
17817,2807901001,119.0,11.956522,9.244402,16.249103,800.000000,625.000000,1150.000000,136.0,12.244898,...,1165.275000,879.148620,1650.000000,169.0,17.815449,12.951090,21.599769,1276.666667,946.774728,1751.136667
17818,2807901002,94.0,11.881313,8.643131,14.586388,631.117480,500.000000,800.000000,107.0,11.944444,...,904.500000,697.713664,1200.000000,137.0,18.283582,14.217458,22.215698,950.000000,760.625000,1273.642186
17819,2807901003,195.0,11.844407,8.498875,15.187166,735.570000,583.333333,900.000000,199.0,12.042993,...,1019.960080,800.000000,1306.887500,246.0,16.787461,12.706313,21.355824,1100.000000,839.002917,1417.887427
17820,2807901004,142.0,12.765957,9.146682,16.666667,758.333333,600.000000,1100.000000,148.0,12.765957,...,1100.000000,816.688889,1688.138812,176.0,17.647059,13.800065,22.919541,1158.325000,850.000000,1739.750629
17821,2807901006,164.0,11.764706,8.565042,14.965986,755.261667,600.000000,966.930879,184.0,12.264151,...,1043.333333,828.560831,1420.924574,233.0,17.116923,13.682190,20.318271,1100.000000,860.895000,1510.135135
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20254,2807921029,77.0,10.673077,8.384765,12.366071,814.583333,561.666667,1000.000000,96.0,10.986877,...,1150.000000,969.368750,1349.022500,89.0,14.268926,13.256086,16.517635,1181.456044,1002.500000,1412.192083
20255,2807921030,118.0,9.558577,7.861635,11.016949,718.333333,563.583008,830.833333,126.0,10.002941,...,900.000000,776.250000,1020.000000,137.0,12.121212,10.747664,13.846154,912.600000,800.000000,1100.000000
20256,2807921031,70.0,10.164196,8.750000,11.382752,750.000000,576.041667,850.000000,76.0,10.280374,...,988.750000,851.041667,1121.707711,164.0,13.265306,11.363208,15.333333,978.516465,871.264409,1172.458333
20257,2807921032,150.0,11.321759,9.333683,13.662440,760.930000,645.780000,927.250000,165.0,11.396060,...,944.737007,800.000000,1187.015259,223.0,15.178571,13.256550,18.976974,967.580282,820.833333,1206.900000
20258,2807921033,90.0,8.960864,8.302629,9.735750,797.603486,691.625000,857.954545,106.0,9.178992,...,1100.000000,917.337363,1266.974653,347.0,13.494000,11.696519,16.887669,1150.000000,950.000000,1385.857664

In [ ]:
#aqui los alquileres ya estan limpios para cruce