In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("demografia.csv", sep=";")
print(df.columns)
df

Index(['Municipios', 'Distritos', 'Secciones', 'Indicadores demográficos',
       'Periodo', 'Total'],
      dtype='str')

,Municipios,Distritos,Secciones,Indicadores demográficos,Periodo,Total
0,"28001 Acebeda, La",NaN,NaN,Edad media de la población,2023,"59,8"
1,"28001 Acebeda, La",NaN,NaN,Edad media de la población,2022,"62,2"
2,"28001 Acebeda, La",NaN,NaN,Edad media de la población,2021,"59,2"
3,"28001 Acebeda, La",NaN,NaN,Edad media de la población,2020,"59,5"
4,"28001 Acebeda, La",NaN,NaN,Edad media de la población,2019,.
...,...,...,...,...,...,...
312853,28903 Tres Cantos,2890301 Tres Cantos distrito 01,2890301027 Tres Cantos sección 01027,Porcentaje de población española,2019,NaN
312854,28903 Tres Cantos,2890301 Tres Cantos distrito 01,2890301027 Tres Cantos sección 01027,Porcentaje de población española,2018,NaN
312855,28903 Tres Cantos,2890301 Tres Cantos distrito 01,2890301027 Tres Cantos sección 01027,Porcentaje de población española,2017,NaN
312856,28903 Tres Cantos,2890301 Tres Cantos distrito 01,2890301027 Tres Cantos sección 01027,Porcentaje de población española,2016,NaN
312857,28903 Tres Cantos,2890301 Tres Cantos distrito 01,2890301027 Tres Cantos sección 01027,Porcentaje de población española,2015,NaN

In [3]:
df_filtrado = df[df["Municipios"].str.contains("^28079 Madrid", case=False, na=False)]

df_filtrado

,Municipios,Distritos,Secciones,Indicadores demográficos,Periodo,Total
81648,28079 Madrid,NaN,NaN,Edad media de la población,2023,"43,9"
81649,28079 Madrid,NaN,NaN,Edad media de la población,2022,"43,9"
81650,28079 Madrid,NaN,NaN,Edad media de la población,2021,"44,0"
81651,28079 Madrid,NaN,NaN,Edad media de la población,2020,"43,8"
81652,28079 Madrid,NaN,NaN,Edad media de la población,2019,"43,6"
...,...,...,...,...,...,...
240088,28079 Madrid,2807921 Madrid distrito 21,2807921034 Madrid sección 21034,Porcentaje de población española,2019,NaN
240089,28079 Madrid,2807921 Madrid distrito 21,2807921034 Madrid sección 21034,Porcentaje de población española,2018,NaN
240090,28079 Madrid,2807921 Madrid distrito 21,2807921034 Madrid sección 21034,Porcentaje de población española,2017,NaN
240091,28079 Madrid,2807921 Madrid distrito 21,2807921034 Madrid sección 21034,Porcentaje de población española,2016,NaN
240092,28079 Madrid,2807921 Madrid distrito 21,2807921034 Madrid sección 21034,Porcentaje de población española,2015,NaN

In [10]:
df_filtrado = df_filtrado[df_filtrado['Periodo'].between(2015,2022)]
print(df_filtrado.isna().sum())  
df_filtrado.head()

Municipios                     0
Distritos                     56
Secciones                   1232
Indicadores demográficos       0
Periodo                        0
Total                       3073
dtype: int64

,Municipios,Distritos,Secciones,Indicadores demográficos,Periodo,Total
81649,28079 Madrid,NaN,NaN,Edad media de la población,2022,"43,9"
81650,28079 Madrid,NaN,NaN,Edad media de la población,2021,"44,0"
81651,28079 Madrid,NaN,NaN,Edad media de la población,2020,"43,8"
81652,28079 Madrid,NaN,NaN,Edad media de la población,2019,"43,6"
81653,28079 Madrid,NaN,NaN,Edad media de la población,2018,"43,6"

In [12]:
df_filtrado['Indicadores demográficos'].unique()

<ArrowStringArray>
[              'Edad media de la población',
 'Porcentaje de población menor de 18 años',
 'Porcentaje de población de 65 y más años',
                   'Tamaño medio del hogar',
      'Porcentaje de hogares unipersonales',
                                'Población',
         'Porcentaje de población española']
Length: 7, dtype: str